media:
  input: src/assets
  output: /assets
content:
  - name: pages
    label: Pages
    path: src
    type: collection
    fields:
      - name: title
        label: Title
        type: string
      - name: layout
        label: Layout
        type: string
        hidden: true
        default: default
      - name: body
        label: Body
        type: rich-text
  - name: sections
    label: Sections
    type: file
    path: src/_data/texts.json
    view:
      fields: [ title, summary ]
    fields:
      - name: title
        label: Title
        type: string
      - name: summary
        label: Summary
        type: text
        options:
          maxlenght: 140
      - name: body
        label: Body
        type: rich-text
  - name: site
    label: Site settings
    path: src/_data/settings.json
    type: file
    fields:
      - name: title
        label: Website title
        type: string
      - name: description
        label: Website description
        type: string
        description: Will be provided for any page with no description.
      - name: site_url
        label: Website URL
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
      - name: socialImage
        label: Social image
        type: image
        description: Image used in the social preview on social networks (e.g. Facebook, Twitter...)
      - name: contact
        label: Contact information
        type: object
        fields:
          - name: twitter
            label: Twitter
            type: string
          - name: phone_call
            label: Phone call
            type: string
          - name: phone_number
            label: Phone number
            type: string
          - name: email
            label: Email
            type: string
          - name: address
            label: Address
            type: object
            fields:
              - name: street
                label: Street
                type: string
              - name: street_number
                label: Street number
                type: string
              - name: postcode
                label: Postcode
                type: string
              - name: city
                label: City
                type: string
      - name: navigation
        label: Navigation
        type: object
        fields:
          - name: label
            label: Link name
            type: string
          - name: url
            label: URL
            type: string
          - name: label
            label: Link name
            type: string
          - name: url
            label: URL
            type: string