media:
  input: src/assets
  output: /assets
content:
  - name: imprint
    label: Imprint
    path: src/imprint.md
    type: file
    fields:
      - { name: title, label: Title, type: string }
      - { name: layout, label: Layout, type: string, hidden: true, default: default }
      - { name: body, label: Body, type: rich-text }
  - name: homepage
    label: Homepage sections
    path: src/_data/texts.json
    type: file
    format: json
    fields:
      - name: about
        label: About
        type: object
        fields:
          - { name: title, label: Title, type: string}
          - { name: paragraph1, label: First paragraph, type: text, options: { maxlenght: 140 } }
          - { name: urlToReadme, label: README URL, type: string}
          - { name: linkToReadme, label: README link text, type: string}
          - { name: paragraph2, label: Second paragraph, type: text, options: { maxlenght: 140 } }
      - name: services
        label: Services
        type: object
        list: true
        fields:
          - { name: title, label: Title, type: string }
          - { name: summary, label: Summary, type: text, options: { maxlenght: 140 } }
      - name: portfolio
        label: Portfolio
        type: object
        list: true
        fields:
          - { name: title, label: Title, type: string }
          - { name: summary, label: Summary, type: text, options: { maxlenght: 140 } }
          - { name: videoID, label: Video ID, type: string }
  - name: site
    label: Site settings
    path: src/_data/settings.json
    type: file
    format: json
    fields:
      - { name: title, label: Website title, type: string }
      - { name: description, label: Website description, type: string, description: Will be provided for any page with no description. }
      - { name: site_url, label: Website URL, type: string }
      - { name: socialImage, label: Social image, type: image, description: Image displayed on social media }
      - name: contact
        label: Contact information
        type: object
        fields:
          - { name: twitter, label: Twitter, type: string }
          - { name: phone_call, label: Phone call, type: string }
          - { name: phone_number, label: Phone number, type: string }
          - { name: email, label: Email, type: string }
          - name: address
            label: Address
            type: object
            fields:
              - { name: street, label: Street, type: string }
              - { name: street_number, label: Street number, type: number }
              - { name: postcode, label: Postcode, type: number, options: { min: 5, max: 7 } }
              - { name: city, label: City, type: string }
      - name: navigation
        label: Navigation
        type: object
        list: true
        fields:
            - { name: label, label: Link name, type: string }
            - { name: url, label: URL, type: string }
