media:
  input: src/assets
  output: /assets
content:
  - name: pages
    label: Pages
    path: src
    type: collection
    fields:
      - name: title
        label: Title
        type: string
      - name: layout
        label: Layout
        type: string
        hidden: true
        default: default
  - name: sections
    label: Sections
    type: file
    path: src/_data/texts.json
    view:
      fields: [ title, summary ]
    fields:
      - name: title
        label: Title
        type: string
      - name: summary
        label: Summary
        type: text
        options:
          maxlenght: 140
      - name: body
        label: Body
        type: rich-text
  - name: site
    label: Site settings
    path: src/_data/settings.json
    type: file
    fields:
      - name: title
        label: Website title
        type: string
      - name: description
        label: Website description
        type: string
        description: Will be provided for any page with no description.
      - name: url
        label: Website URL
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
      - name: socialImage
        label: Social image
        type: image
        description: Image used in the social preview on social networks (e.g. Facebook, Twitter...)